# Generated by Django 3.2.8 on 2021-10-23 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=300, verbose_name='Nome')),
                ('email', models.EmailField(max_length=254, verbose_name='E-Mail')),
                ('texto', models.TextField(verbose_name='Mensagem')),
                ('data_de_criacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
